language: node_js
node_js:
- 0.1
addons:
  code_climate:
    repo_token:
        secure: "b6XBSrOjdrfDdWXq0KdQBdc7yZlXmQ7X+N6qJagZGI8EwuiMRzpQOLq0YUYsa/+r8E2wPy1aSjtTGjtp66pWJiGHgqBsiUDwl9Q2vMi5fsUrCq8qP7O24UkbKFYDklsxgCtWzZB+0uy+d4Xjjl3uKykYFsnh27dxdCyPbEAQlBY="
after_script:
  - cat coverage/lcov.info | codeclimate
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: ASfIqHJlthpK1v+W7ZVJhFhth1OPA1NcJAqADgrdok8zcPTRsbp7y44LIrrBnEF9Pcirb8jAhNquu8VXrXmpbugbGpc4tLdJCfyJWahGE0y9SqoNSm/585fs53VR9tkS0R/+qRl9CwU7rn/L6gUawdwYrYUcsYTqzyMW0O2hHo8=
  app: gapi-sparql
  on:
    repo: pirati-cz/gapi-sparql
