language: node_js
node_js:
- 0.1
deploy:
  provider: heroku
  app: gapi-sparql
  api_key:
    secure: m2hy1Pt5xzZD7SRlsxyRl64aMvtIKYaB44s5lu6U8YypxMWM6po2oH/LQvB25gRlm2w7gAuwes1e0tlP3wkR/7mPkoT/r/FmXA7S9aOj4u+l4l92sAwDcH8AJCrBu3wdRaI4ZoTUmF49q3i5bm6h/Wqrjx9LO+37KXnBDkRkk7Y=
